directories:
  output: dist
  buildResources: build
appId: Agony
extraResources:
  - Bridge.dll
  - Injector.exe
win:
  icon: icon.ico
  publish:
    provider: github
    owner: H3XC0R3
    repo: Agony
  extraResources:
    - ./*.dll
    - ./Injector.exe
electronVersion: 1.8.6
